export enum AppRoutes {
  MAIN = 'main',
  LOGIN = 'login',
  TEST = 'test',
  HOME = 'home',
  Locations = 'locations',
  VirtualMachines = 'virtualMachines',
  Clusters = 'clusters',
  Tags = 'tags',
  Nodes = 'nodes',
  Information = 'information',
  Events = 'events',
  ResourcePool = 'resourcePool',
  CPU = 'cpu',
  Memory = 'memory',
  DISKS = 'disks',
  Luns = 'luns',
  IsoImages = 'isoImages',
  BlockStorages = 'blockStorages',
  TrafficControls = 'trafficControls',
  NetworkSettings = 'networkSettings',
  VirtualNetworks = 'virtualNetworks',
  ExternalNetworks = 'externalNetworks',
  Files = 'files',
  Zfs = 'zfs',
  DataPools = 'dataPools',
  Users = 'users',
  ClusterTransports = 'clusterTransports',
  Monitoring = 'monitoring',
  SecurityEvents = 'securityEvents',
  UserGroups = 'userGroups',
  SecurityUsers = 'securityUsers',
  NtpData = 'ntpData',
  EncryptionKeys = 'encryptionKeys',
  Ssl = 'ssl',
  DirectoryServices = 'directoryServices',
  WebsocketsLog = 'websocketsLog',
  HighAvailability = 'highAvailability',
  Drs = 'drs',
  Connect = 'connect',
  Quorum = 'quorum',
  LimitResource = 'limitResource',
  FileStorage = 'fileStorage',
  BlockStorage = 'blockStorage',
  Volumes = 'volumes',
  Permission = 'permission',
  VmTemplates = 'vmTemplates',
  Tasks = 'tasks',
  Organizations = 'organizations',
  Snapshots = 'snapshots',
  License = 'license',
  System = 'system',
  CdRom = 'cdrom',
  SharedStorages = 'sharedStorages',
  Interfaces = 'interfaces',
  QosPolicy = 'qosPolicy',
  Acpolicies = 'acpolicies',
  MoreEquipment = 'moreEquipment',
  PortsMirroring = 'portsMirroring',
  BootOptions = 'bootOptions',
  VirtualSwitches = 'virtualSwitches',
  SshSettings = 'sshSettings',
  MemoryClean = 'memoryClean',
  ConnectLimit = 'connectLimit',
  Lldp = 'lldp',
  Settings = 'settings',
  Backups = 'backups',
  Roles = 'roles',
  Controller = 'controller',
  Hints = 'hints',
  ScheduledTasks = 'scheduleTasks',
  PublicKeys = 'publicKeys',
  Gateway = 'gateway',
  Services = 'services',
  VmAccess = 'vmAccess',
  Software = 'software',
  Replication = 'replication',
  Sessions = 'sessions',
  AccessControl = 'accessControl',
  Controllers = 'controllers',
  IscsiStorages = 'iscsiStorages',
  Snmp = 'snmp',
  IscsiTarget = 'iscsiTarget',
  PortGroups = 'portGroups',
  Profile = 'profile',
  InfoFc = 'infoFc',
  Smart = 'smart',
  RemoteAccess = 'remoteAccess',
  Keys = 'keys',
  NodeSettings = 'nodeSettings',
  Structure = 'structure',
  ReserveCopy = 'reserveCopy',
  IntegrityControlEvents = 'integrityControlEvents',
  TrustedLoadingsEvents = 'trustedLoadingsEvents',
  ProtectedEnvironmentEvents = 'protectedEnvironmentEvents',
  InternalInterfaces = 'internalInterfaces',
  NodeConnected = 'nodeConnected',
  IntegrityControl = 'integrityControl',
  TrustedLoadings = 'trustedLoadings',
  ProtectedEnvironment = 'protectedEnvironment',
  Smtp = 'smtp',
  SecuritySettings = 'securitySettings',
  UsbDevices = 'usbDevices',
}

export const RoutePath: Record<AppRoutes, string> = {
  [AppRoutes.MAIN]: '/',
  [AppRoutes.LOGIN]: 'login',
  [AppRoutes.TEST]: '/test',
  [AppRoutes.HOME]: '/',
  [AppRoutes.Locations]: 'locations',
  [AppRoutes.VirtualMachines]: 'virtual-machines',
  [AppRoutes.Clusters]: 'clusters',
  [AppRoutes.Tags]: 'tags',
  [AppRoutes.Nodes]: 'nodes',
  [AppRoutes.Information]: 'information',
  [AppRoutes.Events]: 'events',
  [AppRoutes.ResourcePool]: 'resource-pools',
  [AppRoutes.CPU]: 'cpu',
  [AppRoutes.Memory]: 'memory',
  [AppRoutes.DISKS]: 'disks',
  [AppRoutes.Luns]: 'luns',
  [AppRoutes.IsoImages]: 'iso-images',
  [AppRoutes.BlockStorages]: 'block-storages',
  [AppRoutes.TrafficControls]: 'traffic-control',
  [AppRoutes.NetworkSettings]: 'network-settings',
  [AppRoutes.VirtualNetworks]: 'virtual-networks',
  [AppRoutes.ExternalNetworks]: 'external-networks',
  [AppRoutes.Files]: 'files',
  [AppRoutes.Zfs]: 'zfs',
  [AppRoutes.DataPools]: 'data-pools',
  [AppRoutes.Users]: 'users',
  [AppRoutes.ClusterTransports]: 'cluster-transports',
  [AppRoutes.Monitoring]: 'monitoring',
  [AppRoutes.SecurityEvents]: 'security-events',
  [AppRoutes.UserGroups]: 'user-groups',
  [AppRoutes.SecurityUsers]: 'security-users',
  [AppRoutes.NtpData]: 'ntp-data',
  [AppRoutes.EncryptionKeys]: 'encryption-keys',
  [AppRoutes.Ssl]: 'ssl',
  [AppRoutes.DirectoryServices]: 'directory-services',
  [AppRoutes.WebsocketsLog]: 'websockets-log',
  [AppRoutes.HighAvailability]: 'high-availability',
  [AppRoutes.Drs]: 'drs',
  [AppRoutes.Connect]: 'connect',
  [AppRoutes.Quorum]: 'quorum',
  [AppRoutes.LimitResource]: 'limit-resource',
  [AppRoutes.FileStorage]: 'file-storage',
  [AppRoutes.BlockStorage]: 'block-storage',
  [AppRoutes.Volumes]: 'volumes',
  [AppRoutes.Permission]: 'permission',
  [AppRoutes.VmTemplates]: 'vm-templates',
  [AppRoutes.Tasks]: 'tasks',
  [AppRoutes.Organizations]: 'organizations',
  [AppRoutes.Snapshots]: 'snapshots',
  [AppRoutes.System]: 'system',
  [AppRoutes.License]: 'license',
  [AppRoutes.CdRom]: 'cd-rom',
  [AppRoutes.SharedStorages]: 'shared-storages',
  [AppRoutes.Interfaces]: 'interfaces',
  [AppRoutes.QosPolicy]: 'qos-policy',
  [AppRoutes.Acpolicies]: 'acpolicies',
  [AppRoutes.MoreEquipment]: 'more-equipment',
  [AppRoutes.PortsMirroring]: 'ports-mirroring',
  [AppRoutes.BootOptions]: 'boot-options',
  [AppRoutes.VirtualSwitches]: 'virtual-switches',
  [AppRoutes.SshSettings]: 'ssh-settings',
  [AppRoutes.MemoryClean]: 'memory-clean',
  [AppRoutes.ConnectLimit]: 'connect-limit',
  [AppRoutes.Lldp]: 'lldp',
  [AppRoutes.Settings]: 'settings',
  [AppRoutes.Backups]: 'backups',
  [AppRoutes.Roles]: 'roles',
  [AppRoutes.Controller]: 'controller',
  [AppRoutes.Hints]: 'hints',
  [AppRoutes.ScheduledTasks]: 'schedule-tasks',
  [AppRoutes.PublicKeys]: 'public-keys',
  [AppRoutes.Gateway]: 'gateway',
  [AppRoutes.Services]: 'services',
  [AppRoutes.VmAccess]: 'vm-access',
  [AppRoutes.Software]: 'software',
  [AppRoutes.Replication]: 'replication',
  [AppRoutes.Sessions]: 'sessions',
  [AppRoutes.AccessControl]: 'access-control',
  [AppRoutes.Controllers]: 'controllers',
  [AppRoutes.IscsiStorages]: 'iscsi-storages',
  [AppRoutes.Snmp]: 'snmp',
  [AppRoutes.IscsiTarget]: 'iscsi-target',
  [AppRoutes.PortGroups]: 'port-groups',
  [AppRoutes.Profile]: 'profile',
  [AppRoutes.InfoFc]: 'info-fc',
  [AppRoutes.Smart]: 'smart',
  [AppRoutes.RemoteAccess]: 'remote-access',
  [AppRoutes.Keys]: 'keys',
  [AppRoutes.NodeSettings]: 'node-settings',
  [AppRoutes.Structure]: 'structure',
  [AppRoutes.ReserveCopy]: 'reserve-copy',
  [AppRoutes.IntegrityControlEvents]: 'integrity-control-events',
  [AppRoutes.TrustedLoadingsEvents]: 'trusted-loadings-events',
  [AppRoutes.ProtectedEnvironmentEvents]: 'protected-environment-events',
  [AppRoutes.InternalInterfaces]: 'internal-interfaces',
  [AppRoutes.NodeConnected]: 'node-connected',
  [AppRoutes.IntegrityControl]: 'integrity-control',
  [AppRoutes.TrustedLoadings]: 'trusted-loadings',
  [AppRoutes.ProtectedEnvironment]: 'protected-environment',
  [AppRoutes.Smtp]: 'smtp',
  [AppRoutes.SecuritySettings]: 'security-settings',
  [AppRoutes.UsbDevices]: 'usb-devices',
}
